### ISSUE TITLE
[Suggestion] add REI/JEI support

### ISSUE THREAD

**Issue by Bentcheesee** [AstralOrdana/Spelunkery#242]
**Feature:**
Adding in support for REI/JEI to show information tabs about various items as well as visual recipes for grinding things on a Grindstone

**Alternatives:**

I'm not smart, so unfortunately I don't know how to do this

**Additional info:**

At the very least, visual recipes would be very nice to be able to see recipe outputs for various recipes.

also as a side bonus, perhaps make Grindstone recipes compatible with CraftTweaker and/or KubeJS for easy recipe manipulation

**Comment by JubbyDubby** [comment]
Would also really love this. Thanks Astral for your hard work! I'll donate 10 bucks on Kofi once this is added if that helps at all

**Comment by AstralOrdana** [comment]
due to a major change in 1.21 with how recipes work in code, the grindstone polishing recipes will need to be redone completely in the near future. At this point, it wouldnt be worth the effort to add rei support for a recipe that will need to be rewritten so expect it for 1.21 at the earliest

in the meantime i strongly recommend EMI, the recipe viewer i have supported since the start

**Comment by AstralOrdana** [comment]
(closed as its a duplicate of #89)
