### ISSUE TITLE
Allow Name-Named Items to Be Differentiated in Grindstone Loot Tables

### ISSUE THREAD

**Issue by CraftyZombie** [AstralOrdana/Spelunkery#273]
**Feature:**

With the recipe system for grindstones, it was possible to have two different items with the same namespace, yet different IDs grind into different things. As the loot tables only recognize name, and not mod id, this is no longer possible. Could you consider finding some way to return this?

Example:
minecraft:emerald --> minecraft:grass_block
foo:emerald --> minecraft:diamond_block

**Comment by SiverDX** [comment]
doable with sth. like this
~(should be easier than putting the namespace in the loot table filename itself due to modis potentially containing underscores etc.)~
actually the modids wouldn't cause any issues but this probably is easier to read (since it's more clear which item would come from which mod)

```java
        ResourceLocation resource = Utils.getID(itemStack.getItem());
        String directory = resource.getNamespace();
        String file = resource.getPath();

        if (!level.isClientSide()) {
            //find loot table for held item
            String prefix = "gameplay/" + (diamondGrindstone && !depleted ? "diamond_" : "");
            var tablePath = Spelunkery.res(prefix + "grindstone_polishing/" + directory + "/" + file);
```

and move the existing loot tables in the corresponding directories (e.g. `rough_lazurite.json` would go into `/spelunkery/rough_lazurite.json`)

**Comment by CraftyZombie** [comment]
Yeah, this would be awesome.

**Comment by AstralOrdana** [comment]
do you have a specific usecase where you have two items from different mods that use the same name that you want to give distinct grinding recipes to?

**Comment by CraftyZombie** [comment]
No specific use case at the moment, but it could be helpful for example, if two mods with similar features were trying to make an integration.
