### ISSUE TITLE
Some resource names were changed in Create 5.1, causes incompat

### ISSUE THREAD

**Issue by genesy** [AstralOrdana/Spelunkery#78]
♥️

**Comment by genesy** [comment]
nevermind lol

**Comment by SilentSimulacrum** [comment]
Why was this closed?

**Comment by genesy** [comment]
mod owner doesn't care

**Comment by AstralOrdana** [comment]
the create version that makes this change hasnt even been out for a week, excuse me for not immediately releasing an update. The PR hasn't been merged yet because the fabric version of create has not made those changes to the names of items yet and it not worth splitting the version compat for the few weeks or so it will take them to update. Not sure wtf you're going on about me "not caring about valid opinions"

**Comment by genesy** [comment]
It was regarding how OP the dimensional tear was. You said you didn't care on discord so i stopped caring as well

**Comment by AstralOrdana** [comment]
that is completely irrelevant to this issue, please try to keep this issue report page more professional

**Comment by genesy** [comment]
I know that's why i just closed the issue. I just answered your question about wtf i was talking about not caring.

**Comment by AstralOrdana** [comment]
holy shit stop closing this issue, i re-opened it because the create thing isn't resolved, i'll close it when it is

**Comment by AstralOrdana** [comment]
fixed for next release
