### ISSUE TITLE
compatibility with respawn obelisks

### ISSUE THREAD

**Issue by dadoirie** [AstralOrdana/Spelunkery#86]
[respawn obelisks](https://modrinth.com/mod/respawn-obelisks) changes how respawn anchors work and removes the possibility setting those on beds - with spelukery when falling in that fluid that teleports it teleports you to the world spawn - regardless if having already one spawn point set with the respawn obelisks
respawn obelisks is on fabric and forge - I'm using it on fabric 1.19.2

**Comment by AstralOrdana** [comment]
if that mod sets the player's spawnpoint in an abnormal way, there's no simple way for me to add integration. Spelunkery teleports the player to wherever the player's spawnpoint is set so that mod must change something.

**Comment by RedPxnda** [comment]
My mod (respawn obelisks, the mod in question) has a mixin for the `findRespawnPositionAndUseSpawnBlock`(mojmap) static method in `Player`(mojmap).
Idk what you're doing in order to find the player's respawn point, but if you use that method this issue should be fixed.

Essentially, minecraft hardcodes bed and respawn anchors to spawn the player to the side of them, since the actual spawn is marked inside that block(which is unacceptable for any other vanilla blocks).
I mixin here to add similar behavior for my block.

**Comment by AstralOrdana** [comment]
i am using `player.getRespawnPosition();`, you can see it [here](https://github.com/AstralOrdana/Spelunkery/blob/main/common/src/main/java/com/ordana/spelunkery/utils/LevelHelper.java#L58)

**Comment by RedPxnda** [comment]
No, I use `Player#setRespawnPosition` for setting the position- It shouldn't ever be null.

**Comment by RedPxnda** [comment]
I'll have to test around at some point, I'll do that in the near future.

**Comment by RedPxnda** [comment]
@AstralOrdana you can close this. 
Will be fixed(hopefully) in the next update of respawn obelisks.
